# Generated by Django 5.0.3 on 2024-03-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
